package com.mrs.entity;

import jakarta.persistence.*;
import org.springframework.graphql.data.method.annotation.SchemaMapping;

import java.util.UUID;

/**
 * The Movie class represents a movie entity.
 * It is a JPA entity that can be mapped to a table in the database.
 */
@Entity
@Table(name = "movies")
public class Movie {

    // The 'id' field is the primary key for the 'Movie' entity
    @Id // Specifies that this field is the primary key for the entity.
    // Auto-generates the id using the database's identity column (auto-increment).
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private UUID id; // Unique identifier for the movie (automatically generated by the database).

    private String genre; // Represents the genre of the movie (e.g., action, drama, comedy).
    private String title; // Represents the title of the movie.
    private String director; // Represents the director of the movie.
    private String releaseDate; // Represents the release date of the movie in a LocalDate format.

    public Movie(UUID id) {
        this.id = id;
    }

    public Movie(String genre, String title, String director, String releaseDate) {
        this.genre = genre;
        this.title = title;
        this.director = director;
        this.releaseDate = releaseDate;
    }

    public Movie() {}

    // Setter method for the 'id' field
    public void setId(UUID id) {
        this.id = id; // Sets the unique ID for the movie.
    }

    // Setter method for the 'genre' field
    public void setGenre(String genre) {
        this.genre = genre; // Sets the genre of the movie.
    }

    // Setter method for the 'title' field
    public void setTitle(String title) {
        this.title = title; // Sets the title of the movie.
    }

    // Setter method for the 'director' field
    public void setDirector(String director) {
        this.director = director; // Sets the director's name.
    }

    // Setter method for the 'releaseDate' field
    public void setReleaseDate(String releaseDate) {
        this.releaseDate = releaseDate; // Sets the release date of the movie.
    }

    // Getter method for the 'id' field
    public UUID getId() {
        return id; // Returns the unique ID for the movie.
    }

    // Getter method for the 'genre' field
    public String getGenre() {
        return genre; // Returns the genre of the movie.
    }

    // Getter method for the 'title' field
    public String getTitle() {
        return title; // Returns the title of the movie.
    }

    // Getter method for the 'director' field
    public String getDirector() {
        return director; // Returns the name of the director.
    }

    // Getter method for the 'releaseDate' field
    public String getReleaseDate() {
        return releaseDate; // Returns the release date of the movie.
    }
}
