package com.mrs;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import java.time.LocalDate; // Import LocalDate to handle the movie's release date

/**
 * The Movie class represents a movie entity.
 * It is a JPA entity that can be mapped to a table in the database.
 */
@Entity
public class Movie {

    // The 'id' field is the primary key for the 'Movie' entity
    @Id // Specifies that this field is the primary key for the entity.
    // Auto-generates the id using the database's identity column (auto-increment).
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // Unique identifier for the movie (automatically generated by the database).

    private String genre; // Represents the genre of the movie (e.g., action, drama, comedy).
    private String title; // Represents the title of the movie.
    private String director; // Represents the director of the movie.
    private LocalDate releaseDate; // Represents the release date of the movie in a LocalDate format.

    // Setter method for the 'id' field
    public void setId(Long id) {
        this.id = id; // Sets the unique ID for the movie.
    }

    // Setter method for the 'genre' field
    public void setGenre(String genre) {
        this.genre = genre; // Sets the genre of the movie.
    }

    // Setter method for the 'title' field
    public void setTitle(String title) {
        this.title = title; // Sets the title of the movie.
    }

    // Setter method for the 'director' field
    public void setDirector(String director) {
        this.director = director; // Sets the director's name.
    }

    // Setter method for the 'releaseDate' field
    public void setReleaseDate(LocalDate releaseDate) {
        this.releaseDate = releaseDate; // Sets the release date of the movie.
    }

    // Getter method for the 'id' field
    public Long getId() {
        return id; // Returns the unique ID for the movie.
    }

    // Getter method for the 'genre' field
    public String getGenre() {
        return genre; // Returns the genre of the movie.
    }

    // Getter method for the 'title' field
    public String getTitle() {
        return title; // Returns the title of the movie.
    }

    // Getter method for the 'director' field
    public String getDirector() {
        return director; // Returns the name of the director.
    }

    // Getter method for the 'releaseDate' field
    public LocalDate getReleaseDate() {
        return releaseDate; // Returns the release date of the movie.
    }
}
